import { describe, expect, test } from 'vitest';
import * as reactIndex from '../src/react';
import * as shadcnClient from '../src/react/client/shadcn';

const expectedExports = [
  'Alert',
  'AlertDescription',
  'AlertTitle',
  'ArticleHeader',
  'Badge',
  'Button',
  'Callout',
  'Card',
  'CardContent',
  'CardDescription',
  'CardFooter',
  'CardHeader',
  'CardSkeleton',
  'CardTitle',
  'CategoryPill',
  'Checkbox',
  'CodeBlock',
  'DEFAULT_ACCENT',
  'DEFAULT_MODE',
  'FeaturedPostCard',
  'FileInput',
  'Footer',
  'Header',
  'Hero',
  'Icon',
  'Input',
  'Layout',
  'Lead',
  'Logo',
  'NativeSelect',
  'PostCard',
  'PostGrid',
  'Prose',
  'READING_PROGRESS_VAR',
  'RadioGroup',
  'RadioGroupItem',
  'Separator',
  'Sidebar',
  'SidebarSection',
  'Skeleton',
  'Table',
  'TableBody',
  'TableCaption',
  'TableCell',
  'TableFooter',
  'TableHead',
  'TableHeader',
  'TableRow',
  'Textarea',
  'ThemeScript',
  'accentNames',
  'accents',
  'accentsInk',
  'articleHeader',
  'articleHeaderClasses',
  'callout',
  'calloutClasses',
  'calloutLabels',
  'cardSkeleton',
  'categoryPill',
  'categoryPillClasses',
  'codeBlock',
  'codeBlockClasses',
  'colors',
  'cx',
  'defaultCategoryColors',
  'durations',
  'easings',
  'featuredPostCard',
  'featuredPostCardClasses',
  'field',
  'fieldClasses',
  'fieldMessage',
  'fontFamilies',
  'fontSizes',
  'fontWeights',
  'footer',
  'footerClasses',
  'header',
  'headerClasses',
  'hero',
  'heroClasses',
  'layout',
  'letterSpacings',
  'lineHeights',
  'logo',
  'logoClasses',
  'postCard',
  'postCardClasses',
  'postGrid',
  'prose',
  'proseClasses',
  'radii',
  'readingProgress',
  'readingProgressClasses',
  'resolveAccentColor',
  'resolveCategoryColor',
  'semantic',
  'semanticInk',
  'sidebar',
  'sidebarClasses',
  'skeletonLine',
  'spacing',
  'table',
  'tableClasses',
  'tableOfContents',
  'themeModes',
  'tocLink',
  'zIndex',
] as const;

// Server-safe primitives added by this feature (form/data primitives, FDP-13):
// text fields, choice controls and the Table family, plus the recipes behind
// them. These are the names that must NOT leak into the client-only shadcn
// barrel (AD-002 — server is where they belong).
const newServerSafePrimitives = [
  'Textarea',
  'NativeSelect',
  'FileInput',
  'Checkbox',
  'RadioGroup',
  'RadioGroupItem',
  'Table',
  'TableHeader',
  'TableBody',
  'TableFooter',
  'TableRow',
  'TableHead',
  'TableCell',
  'TableCaption',
] as const;

describe('react/index server-safe barrel', () => {
  test.each(expectedExports)('exports %s as a defined value', (name) => {
    expect(reactIndex[name as keyof typeof reactIndex]).toBeDefined();
  });

  test('exports exactly the expected named bindings (no forgotten or accidental exports)', () => {
    expect(Object.keys(reactIndex).sort()).toEqual([...expectedExports].sort());
  });

  test.each(newServerSafePrimitives)(
    'does not leak %s into the client-only shadcn barrel (AD-002)',
    (name) => {
      expect(Object.keys(shadcnClient)).not.toContain(name);
    },
  );
});
